### ISSUE TITLE
Add Python competitive programming questions with answers

### ISSUE THREAD

**Issue by jayadevvasudevan** [jayadevvasudevan/basic-python#16]
hi guys if you find any competitive programming questions you can add them on this repo

**Comment by Jibendu007** [comment]
okay

**Comment by Anubha13kumari** [comment]
I want to work on this.

**Comment by MrRobot3301** [comment]
My PR is now showing

**Comment by ruhi052001** [comment]
i want to work on this

**Comment by AnujSaha0111** [comment]
I want to work on it, can you please assign it to me

**Comment by jayadevvasudevan** [comment]
> I want to work on it, can you please assign it to me

you can create a new branch and add your programs'

**Comment by AnujSaha0111** [comment]
Created the pull  request..to merge them

**Comment by halcyon-past** [comment]
I want to add "Check If Array Pairs Are Divisible by k" which is leetcode's problem of the day for today
