### ISSUE TITLE
ADD basic python programs

### ISSUE THREAD

**Issue by jayadevvasudevan** [jayadevvasudevan/basic-python#4]
hi guys add any python programs you want in here and this is to support hacktober fest contribution

**Comment by wimanshaherath** [comment]
Can you assign me on this issue?

**Comment by wimanshaherath** [comment]
Thank you!

**Comment by sohambodas** [comment]
One pf my pull requests got merged by u, however the hacktoberfest site says, "project not participating. What could be the reason. 
@jayadevvasudevan 
Thanks.

**Comment by jayadevvasudevan** [comment]
okay think its because i didn't add the hactober fest tags

**Comment by jayadevvasudevan** [comment]
you can add new file sqrt2 with same code
ill delete the old one after that

**Comment by gauravs1303** [comment]
Can you assign me?

**Comment by jayadevvasudevan** [comment]
@gauravs1303 you can add the programs ill add the tag on to it

**Comment by rohan26062001** [comment]
I would like to contribute

**Comment by aryacodez** [comment]
I would like to contribute can u assign me

**Comment by jayadevvasudevan** [comment]
hi everyone you can contribute the code . I'll add the hacktoberfest tag while merging

**Comment by Anubha13kumari** [comment]
i want to work on this.

**Comment by aryacodez** [comment]
My pull request is showing **Project not Participating**

**Comment by Suryageeks** [comment]
I want to contribute to this repo

**Comment by AnujSaha0111** [comment]
Can you please assign it to me, I want to contribute

**Comment by jayadevvasudevan** [comment]
> Can you please assign it to me, I want to contribute

you can create and new branch and add them

**Comment by AnujSaha0111** [comment]
Created the pull request..to merge them

**Comment by satyam1024** [comment]
I would like to contribute  to this repo. please assign it to me.

**Comment by AnujSaha0111** [comment]
I want to contribute to the repo and I have created the pull request for the same.

**Comment by satyam1024** [comment]
Hi @jayadevvasudevan,
I've submitted pull request #76. Could you please tag it as hacktoberfest-accepted? Thank you!

**Comment by AnujSaha0111** [comment]
I have also submitted the pull request. Can you merge it for Hacktoberfest
