### ISSUE TITLE
python file handling programs

### ISSUE THREAD

**Issue by jayadevvasudevan** [jayadevvasudevan/basic-python#77]
Hi, 
requesting python file handling programs

**Comment by aaronwrites** [comment]
Hello, Kindly assign this issue to me please.

**Comment by jayadevvasudevan** [comment]
you can add programs by forking and creating merge requests. needed more than 1 file handling program. will add the badge when merging @aaronwrites

**Comment by aaronwrites** [comment]
Got it!! Thanks @jayadevvasudevan
