### ISSUE TITLE
Image scrapper using python

### ISSUE THREAD

**Issue by jayadevvasudevan** [jayadevvasudevan/basic-python#97]

**Comment by ExPl0iT-29** [comment]
hey,
i can work on this just add some more information about it.
Thanks

**Comment by jayadevvasudevan** [comment]
an image scrapper where we can specify the type of image to be scrapped something like that. you are free to add any image scrapper even simple program is fine

**Comment by ExPl0iT-29** [comment]
oh, alright sir.
Please assign me to it.
Thanks <3
